version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: assistencia_tecnica
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M # Limita o Postgres a no máximo 512MB de RAM
    networks:
      - api-network

  app:
    build: .
    container_name: assistencia_tecnica_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/assistencia_tecnica
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    deploy:
      resources:
        limits:
          memory: 1G # Limita o Java a no máximo 1GB de RAM
    networks:
      - api-network

volumes:
  postgres_data:

networks:
  api-network:
    driver: bridge